core:Core{
    domain:Domain{
        doc:Doc  
        engine:Engine
        functions:Functions{
            scene:Scene
            move:Move FX
        }
        fixture:Fixture

        cmd:DocCommand
        cmd.shape:oval
        out:OutputPlugin
        out.shape:oval
    }

    app:Application{
        add_function->_.domain.cmd:{
            target-arrowhead.style.filled:false
            target-arrowhead.shape:diamond
        }
        timeline:TimeLine{
            add_track->_._.domain.cmd:{
                target-arrowhead.style.filled:false
                target-arrowhead.shape:diamond
            }
        remove_track->_._.domain.cmd:{
                target-arrowhead.style.filled:false
                target-arrowhead.shape:diamond
            }
        }
    }
}

infra:Infrastructure{
    dmx:DMX Plugin
    dmx->_.core.domain.out:{
        target-arrowhead.style.filled:false
        target-arrowhead.shape:diamond
    }

    artnet:ArtNet Plugin
    artnet->_.core.domain.out:{
        target-arrowhead.style.filled:false
        target-arrowhead.shape:diamond
    }

    serializer:Serializer
    serializer->_.core.domain
}

ui:Slint UI{
    preview:Preview Plugin
    preview->_.core.domain.out:{
        target-arrowhead.style.filled:false
        target-arrowhead.shape:diamond
    }
}

ui->core.app