---
title: Objects and Views
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    direction LR

    namespace Objects{
        class Fixture

        class FixtureDef

        class FixtureGroup

        class Universe

        class Function

        class FunctionGroup

        class Output

        class Widget

        class Palette
    }

    %% Object-Object Relationships
    Universe "1" -->  "*" Fixture
    FixtureGroup "1" --> "*" Fixture
    Universe "1" --> "*" Output
    FunctionGroup "1" --> "*" Function
    Function "1" --> "1" FixtureGroup
    Fixture "1" --> "1" FixtureDef

    namespace Views{
        class UniverseView
        class 2DView
        class 3DView
        class FunctionListView
        class FunctionView
        class VirtualConsoleView
        class PaletteView 
        class TimelineView
    }

    %% Object-View Relationships
    UniverseView "1" --> "1" Universe
    UniverseView "1" --> "*" Fixture
    2DView "1" --> "*" Fixture
    3DView "1" --> "*" Fixture
    FunctionListView "1" --> "*" Function
    FunctionView "1" --> "1" Function
    VirtualConsoleView "1" --> "*" Widget
    PaletteView "1" --> "1" Palette

