import { Palette, StyleMetrics, TabWidget, Slider } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";
import { Icons } from "../styling.slint";

export struct FaderValues {
    dimmer: int,
    color-r: int,
    color-g: int,
    color-b: int}

export global FadersStore {
    in-out property <FaderValues> values;
    in property <string> selected-fixture;
    callback value-changed(string, string, int);
    // fixture-id, channel, value
}

component Fader {
    in property <image> icon;
    in property <length> slider-height;
    callback value-changed(float);
    VerticalLayout {
        Image {
            source: icon;
        }

        slider := Slider {
            orientation: Orientation.vertical;
            minimum: 0;
            maximum: 255;
            height: root.slider-height;
            changed(value) => value-changed(value);
        }

        PlaneText {
            text: round(slider.value);
        }
    }
}

export component FadersView inherits Rectangle {
    in property <string> fixture-id <=> FadersStore.selected-fixture;
    //TODO: bottom-panel経由で受け取る
    property <FaderValues> values <=> FadersStore.values;

    VerticalLayout {
        MiddleText {
            text: @tr("Function");
        }

        TabWidget {
            orientation: Orientation.vertical;
            Tab {
                title: @tr("Dimmer");
                Fader {
                    icon: Icons.dimmer;
                    slider-height: parent.height * 0.8;
                    value-changed(value) => {
                        root.values.dimmer = round(value);
                        FadersStore.value-changed(fixture-id, "Dimmer",value);
                    }
                }
            }

            Tab {
                title: @tr("Color");
                property <length> slider-height: self.height * 0.8;
                HorizontalLayout {
                    Fader {
                        slider-height: 80px;
                        value-changed(value) => {
                            root.values.color-r = round(value);
                            FadersStore.value-changed(fixture-id, "Red",value);
                        }
                    }

                    Fader {
                        //slider-height: slider-height;
                        value-changed(value) => {
                            root.values.color-g = round(value);
                            FadersStore.value-changed(fixture-id, "Green",value);
                        }
                    }

                    Fader {
                        //slider-height: slider-height;
                        value-changed(value) => {
                            root.values.color-b = round(value);
                            FadersStore.value-changed(fixture-id, "Blue",value);
                        }
                    }
                }
            }

            Tab {
                title: @tr("Position");
                Rectangle {
                    PlaneText {
                        text: "position";
                    }
                }
            }

            Tab {
                title: @tr("Gobo");
                Rectangle {
                    PlaneText {
                        text: "gobo";
                    }
                }
            }
        }
    }
}
