import { Icons } from "../styling.slint";
import { Palette, ScrollView } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FixtureModel {
    id:string,
    name:string,
    modes: [string]
    }

export struct ManufacturerModel {
    manufacturer:string,
    fixtures:[FixtureModel],
    expanded:bool,
}

component FixtureListItem inherits Rectangle {
    in property <string> fixture-name;
    in property <string> fixture-id;
    in property <bool> selected;
    callback clicked();

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        spacer := Rectangle {
            width: 2rem;
        }

        PlaneText {
            text: fixture-name;
        }
    }

    states [
        selected when selected: {
            background: Palette.alternate-background;
        }
    ]

    TouchArea {
        clicked => root.clicked();
    }

    /*DragArea {
        mime-type: "text/plain";
        data: fixture-id;
    }*/

    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Rename fixture definition");
                activated => {
                    debug("rename requested");
                }
            }

            MenuItem {
                title: @tr("Remove fixture definition");
                activated => {
                    debug("remove requested");
                }
            }
        }
    }
}

export component FixtureListView inherits Rectangle {
    in property <[ManufacturerModel]> manufacturers;
    out property <string> selected-fixture-id;

    ScrollView {
        vertical-scrollbar-policy: ScrollBarPolicy.always-on;
        VerticalLayout {
            alignment: LayoutAlignment.start;
            for manufacturer-model in manufacturers: Rectangle {
                VerticalLayout {
                    header := Rectangle {
                        HorizontalLayout {
                            Image {
                                source: manufacturer-model.expanded ? Icons.arrow-drop-down : Icons.arrow-right;
                                width: 22px;
                                height: 22px;
                                vertical-alignment: center;
                            }

                            MiddleText {
                                text: manufacturer-model.manufacturer;
                            }
                        }

                        TouchArea {
                            width: parent.width;
                            height: parent.height;
                            clicked => {
                                manufacturer-model.expanded = !manufacturer-model.expanded
                            }
                        }
                    }

                    if manufacturer-model.expanded:VerticalLayout {
                        alignment: LayoutAlignment.start;
                        for fixture in manufacturer-model.fixtures: item := FixtureListItem {
                            fixture-name: fixture.name;
                            fixture-id: fixture.id;
                            selected: selected-fixture-id == fixture.id;
                            clicked => {
                                selected-fixture-id = fixture.id;
                            }
                        }
                    }
                }
            }
        }
    }
}
