import { FixtureListView } from "fixture-list-view.slint";
import { BorderHorz } from "../styling.slint";
import { FixtureSingleView } from "fixture-single-view.slint";
export component FixtureView inherits VerticalLayout {
    property <string> selected-fixture-id <=> list-view.selected-fixture-id;

    list-view := FixtureListView { }

    BorderHorz { }

    FixtureSingleView {
        fixture-id: selected-fixture-id;
    }
}
