import { Icons } from "../styling.slint";
import { Palette } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FixtureModel {
    id:string,
    name:string}

export struct ManufacturerModel {
    manufacturer:string,
    fixtures:[FixtureModel],
    expanded:bool,
}

export global FixtureListStore {
    in property <[ManufacturerModel]> model:[
        {
            manufacturer:"Stage Evolution",
            fixtures:[{ name:"HPAR64-9" }, { name:"ORION WH" }, { name:"IM-MH90S" }],
            expanded:false
        },
        { manufacturer:"IM-Relax", fixtures:[{ name:"IM-MH90S" }], expanded:false }
    ];
}

export component FixtureListView inherits Rectangle {
    out property <string> selected-fixture-id;
    VerticalLayout {
        alignment: LayoutAlignment.start;
        for manufacturer-model in FixtureListStore.model: Rectangle {
            VerticalLayout {
                header := Rectangle {
                    HorizontalLayout {
                        Image {
                            source: manufacturer-model.expanded ? Icons.arrow-drop-down : Icons.arrow-right;
                            width: 22px;
                            height: 22px;
                            vertical-alignment: center;
                        }

                        MiddleText {
                            text: manufacturer-model.manufacturer;
                        }
                    }

                    TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => {
                            manufacturer-model.expanded = !manufacturer-model.expanded
                        }
                    }
                }

                if manufacturer-model.expanded:VerticalLayout {
                    alignment: LayoutAlignment.start;
                    for fixture in manufacturer-model.fixtures: item := Rectangle {
                        HorizontalLayout {
                            alignment: LayoutAlignment.start;
                            spacer := Rectangle {
                                width: 2rem;
                            }

                            PlaneText {
                                text: fixture.name;
                            }
                        }

                        TouchArea {
                            clicked => {
                                item.background = Palette.alternate-background;
                                selected-fixture-id = fixture.id;
                            }
                        }

                        DragArea {
                            mime-type: "text/plain";
                            data: fixture.id;
                        }

                        ContextMenuArea {
                            Menu {
                                MenuItem {
                                    title: @tr("Rename fixture definition");
                                    activated => {
                                        debug("rename requested");
                                    }
                                }

                                MenuItem {
                                    title: @tr("Remove fixture definition");
                                    activated => {
                                        debug("remove requested");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
