import { Palette } from "std-widgets.slint";
import { MiddleText } from "../parts/texts.slint";

export struct FixtureEntityData {
    fixture-id:string,
    x:length,
    y:length,
    color:brush
}

export global Preview2DLogic {
    in property <[FixtureEntityData]> fixture-list:[
        {
            fixture-id:"",
            x:1px,
            y:1px,
            color:rgb(255,0,0)
        },
        {
            fixture-id:"",
            x:70px,
            y:60px,
            color:rgb(0,0,255)
        }
    ];
}

export component Preview2D inherits Rectangle {
    VerticalLayout {
        title := MiddleText {
            text: @tr("Preview");
        }

        body := Rectangle {
            for fixture in Preview2DLogic.fixture-list: fixture-rect := Rectangle {
                property <bool> selected;
                x: fixture.x;
                y: fixture.y;
                selected: false;
                width: 70px;
                height: 70px;
                background: fixture.color;
                border-radius: self.width/2;

                states [
                    active when selected: {
                        fixture-rect.border-width: 2px;
                        fixture-rect.border-color: Palette.accent-foreground;
                    }
                    inactive when !selected: {
                        fixture-rect.border-width: 1px;
                        fixture-rect.border-color: Palette.border;
                    }
                ]
                ta := TouchArea {
                    clicked => {
                        fixture-rect.selected = !fixture-rect.selected;
                    }
                }
            }
        }
    }
}
