import { StyleMetrics, Palette, ScrollView } from "std-widgets.slint";
import { BorderHorz, BorderVert } from "../styling.slint";

export struct UniverseViewFixtureModel {
    fixture-id:string,
    name:string,
    address:int,
    footprint:int}

export global UniverseViewStore {
    in property <[UniverseViewFixtureModel]> fixtures:[{ name:"MyFixture", address:12, footprint:5 }];
}

export component UniverseView inherits Rectangle {
    property <length> grid-width: 26px;
    //max(26px, root.width / root.col-num);
    // FIXME: magic number
    property <length> grid-height: 26px;
    //max(26px, root.height / root.row-num);
    property <int> col-num: 32;
    property <int> row-num: 16;

    background: Palette.background;
    //ScrollView {
    VerticalLayout {
        for num[i] in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]: VerticalLayout {
            HorizontalLayout {
                for num2[j] in [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32
                ]: HorizontalLayout {
                    Rectangle {
                        width: root.grid-width - 1px; //TODO: レスポンシブにしたい
                        height: root.grid-height - 1px;
                        background: Palette.alternate-background;
                        Text {
                            text: (num - 1) * root.col-num + num2;
                        }
                    }

                    if j != root.col-num:BorderVert {
                        width: 1px;
                    }
                }
            }

            if i != root.row-num:BorderHorz {
                height: 1px;
            }
        }
    }

    for fxt in UniverseViewStore.fixtures: Rectangle {
        x: round(mod(fxt.address,root.col-num)) * root.grid-width;
        y: round(fxt.address / root.col-num) * grid-height;
        width: fxt.footprint * grid-width;
        height: grid-height;
        background: Palette.accent-background;
        Text {
            text: fxt.name;
            color: Palette.foreground;
        }
    }
}
