import {
    FixtureListView,
    ManufacturerModel,
} from "../views/fixture-list-view.slint";
import { BorderHorz, BorderVert } from "../styling.slint";
import { FixtureSingleView } from "../views/fixture-single-view.slint";
import { MiddleText } from "../parts/texts.slint";
import { StandardButton } from "std-widgets.slint";
import { GlobalMessage } from "../global-state.slint";


export global FixtureListStore {
    in property <[ManufacturerModel]> model:[
        // dummy model
        {
            manufacturer:"Stage Evolution",
            fixtures:[{ name:"HPAR64-9" }, { name:"ORION WH" }, { name:"IM-MH90S" }],
            expanded:false
        },
        { manufacturer:"IM-Relax", fixtures:[{ name:"IM-MH90S" }], expanded:false }
    ];
    /// Returns error message. Empty when there's no error.
    callback patch(universe: string, address: int, fixture-id: string, mode: string, pos: Point) -> string;
    callback get-modes(fixture-def-id: string) -> [string];
    callback get-next-address(universe: string) -> int;
}

export component FixtureDefPanel inherits VerticalLayout {
    property <string> selected-fixture-id <=> list-view.selected-fixture-id;
    property <[string]> fixture-modes-cache;
    property <int> next-address-cache;

    init => {
        // TODO: hard code
        next-address-cache = FixtureListStore.get-next-address("Universe 1");
    }

    changed selected-fixture-id => {
        fixture-modes-cache = FixtureListStore.get-modes(selected-fixture-id);
    }

    animate width { duration: 250ms; }

    MiddleText {
        text: @tr("Fixture Definitions");
    }

    list-view := FixtureListView {
        manufacturers: FixtureListStore.model;
    }

    BorderHorz { }

    if selected-fixture-id != "":FixtureSingleView {
        fixture-id: selected-fixture-id;
        // TODO: hard code
        universes: ["Universe 1", "Universe 2"];
        modes: fixture-modes-cache;
        address-default: next-address-cache;

        changed selected-universe => {
            next-address-cache = FixtureListStore.get-next-address(self.selected-universe);
        }

        patch(universe, address, fixture-id, mode, pos) => {
            GlobalMessage.error-message = FixtureListStore.patch(universe, address, fixture-id, mode,pos);
            if GlobalMessage.error-message == "" {
                next-address-cache = FixtureListStore.get-next-address(self.selected-universe);
            }
        }
    }
}
