import { Palette, StyleMetrics, TabWidget, Slider } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FaderValues {
    dimmer: int,
    color-r: int,
    color-g: int,
    color-b: int}

export global FaderLogic {
    in-out property <FaderValues> values;
    callback value-changed(string, string, int);
    // fixture-id, channel, value
}

export component FadersView inherits Rectangle {
    in property <string> fixture-id;
    property <FaderValues> values <=> FaderLogic.values;

    VerticalLayout {
        MiddleText {
            text: @tr("Function");
        }

        TabWidget {
            orientation: Orientation.vertical;
            Tab {
                title: @tr("Dimmer");
                VerticalLayout {
                    slider := Slider {
                        orientation: Orientation.vertical;
                        minimum: 0;
                        maximum: 255;
                        height: 65%;
                        changed(value) => {
                            root.values.dimmer = round(value);
                            FaderLogic.value-changed(fixture-id,"dimmer",value);
                        }
                    }

                    Text {
                        text: round(slider.value);
                    }
                }
            }

            Tab {
                title: @tr("Color");
                Rectangle {
                    PlaneText {
                        text: "color";
                    }
                }
            }

            Tab {
                title: @tr("Position");
                Rectangle {
                    PlaneText {
                        text: "position";
                    }
                }
            }

            Tab {
                title: @tr("Gobo");
                Rectangle {
                    PlaneText {
                        text: "gobo";
                    }
                }
            }
        }
    }
}
