import { Palette, StyleMetrics, TabWidget, Slider } from "std-widgets.slint";
import { PlaneText, MiddleText } from "../parts/texts.slint";

export struct FaderValues {
    dimmer: int,
    color-r: int,
    color-g: int,
    color-b: int
}

export global FaderLogic {
    in-out property <FaderValues> values;
    callback value-changed();
}

export component FadersView inherits Rectangle {
    in property <string> fixture-id;
    property <FaderValues> values <=> FaderLogic.values;

    changed values => FaderLogic.value-changed();

    VerticalLayout {
        MiddleText {
            text: @tr("Function");
        }

        TabWidget {
            orientation: Orientation.vertical;
            Tab {
                title: @tr("Dimmer");
                Rectangle {
                    Slider {
                        orientation: Orientation.vertical;
                        minimum: 0;
                        maximum: 255;
                        height: 65%;
                        transform-rotation: 180deg;
                        changed(value) => {
                            root.values.dimmer=round(value);
                        }
                    }
                }
            }

            Tab {
                title: @tr("Color");
                Rectangle {
                    PlaneText {
                        text: "color";
                    }
                }
            }

            Tab {
                title: @tr("Position");
                Rectangle {
                    PlaneText {
                        text: "position";
                    }
                }
            }

            Tab {
                title: @tr("Gobo");
                Rectangle {
                    PlaneText {
                        text: "gobo";
                    }
                }
            }
        }
    }
}
