import { Icons } from "../styling.slint";
import { TkText } from "../parts/tk-text.slint";
import { Palette } from "std-widgets.slint";

export struct Fixture {
    name:string
}

export struct FixtureListModel {
    manufacturer:string,
    fixtures:[Fixture],
    expanded:bool,  
}

export global FixtureListViewLogic {
    in property <[FixtureListModel]> fixtures:[
        {
            manufacturer:"Stage Evolution",
            fixtures:[
                {name:"HPAR64-9"},
                {name:"ORION WH"},
                {name:"IM-MH90S"}
            ],
            expanded:false
        },
        {
            manufacturer:"IM-Relax",
            fixtures:[
                {name:"IM-MH90S"}
            ],
            expanded:false
        }
    ];
}

export component FixtureListView inherits Rectangle{

    VerticalLayout {
        alignment: LayoutAlignment.start;
        for map in FixtureListViewLogic.fixtures: Rectangle {        
            VerticalLayout {
                header:=Rectangle {
                    HorizontalLayout {
                        Image {
                            source: map.expanded?Icons.arrow-drop-down:Icons.arrow-right;
                            width: 1.5rem;
                            height: 1.5rem;
                        }
                        TkText {
                            text: map.manufacturer;
                        }
                    }
                    TouchArea {
                        width:parent.width;
                        height: parent.height;
                        clicked => {
                            debug("clicked");
                            map.expanded=!map.expanded
                        }
                    }
                }
                
                if map.expanded:VerticalLayout{
                    alignment: LayoutAlignment.start;
                    for fixture in map.fixtures:HorizontalLayout{
                        alignment: LayoutAlignment.start;

                        spacer:=Rectangle {
                            width: 2rem;
                        }
                        TkText {
                            text: fixture.name;
                        }
                        /*DragArea{
                            mime-type:"text/plain";
                            data:fixture.name;
                        }*/
                    }
                }
            }
        }
    }   
}