import { Palette, StyleMetrics, TabWidget } from "std-widgets.slint";
import { MiddleText, PlaneText } from "../styling.slint";
export component FunctionView inherits Rectangle {
    in property <string> fixture-id;
    VerticalLayout {
        MiddleText {
            text: @tr("Function");
        }

        TabWidget {
            orientation: Orientation.vertical;
            Tab {
                title: @tr("Dimmer");
                Rectangle {
                    PlaneText {
                        text: "dimmer";
                    }
                }
            }

            Tab {
                title: @tr("Color");
                Rectangle {
                    PlaneText {
                        text: "color";
                    }
                }
            }

            Tab {
                title: @tr("Position");
                Rectangle {
                    PlaneText {
                        text: "position";
                    }
                }
            }

            Tab {
                title: @tr("Gobo");
                Rectangle {
                    PlaneText {
                        text: "gobo";
                    }
                }
            }
        }
    }
}
