import { Palette } from "std-widgets.slint";
import { LargeText, MiddleText } from "../styling.slint";

export struct FixtureEntity {
    x:length,
    y:length,
    color:brush
}

export global Preview2DLogic {
    in property <[FixtureEntity]> fixture-list:[
        {
            x:1px,
            y:1px,
            color:rgb(255,0,0)
        },
        {
            x:70px,
            y:60px,
            color:rgb(0,0,255)
        }
    ];
}

export component Preview2D inherits Rectangle{
    VerticalLayout {
        title:=MiddleText {
            text: "Preview";
        }
        body:=Rectangle {
            for fixture in Preview2DLogic.fixture-list: Rectangle {
                x: fixture.x;
                y: fixture.y;
                width: 15px;
                height: 15px;
                background: fixture.color;
                border-width: 1px;
                border-color: Palette.border;
                border-radius: 25px;
            }
        }
    }
}