import { StyleMetrics, Palette } from "std-widgets.slint";

export component UniverseView inherits Rectangle {
    background: Palette.background;

    HorizontalLayout {
        for num[i] in [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]: Rectangle {
            VerticalLayout {
                for num2[j] in[1,2,3,4,5,6,7,8,9,10]:Rectangle{
                    width: 3rem;
                    height: 3rem;
                    background: Palette.foreground;
                    border-width: 1px;
                    border-color: Palette.border;
                }
            }
        }
    }
}


