import { Button,TabWidget,  Palette } from "std-widgets.slint";
import { FixturesTab } from "fixtures-tab.slint";
import { FunctionsTab } from "functions-tab.slint";
import { VirtualConsoleTab } from "virtual-console-tab.slint";
import { Preview2D } from "views/preview-2d.slint";
import { FunctionView } from "views/function-view.slint";
import { Icons } from "styling.slint";
import { TopBar } from "top-bar.slint";
import { TimeLineView } from "views/timeline-view.slint";

export global MenuBarActions {
    callback save();
    callback save-as();
}
component HorizontalSplit inherits Rectangle {
    property<float> proportion: 50%;
    property<float> actual_proportion: handle.pressed ? handle.new_proportion : proportion;

    

    r1 := Rectangle {
        height: 100%;
        width: actual_proportion * parent.width -  handle.width/2;
        TouchArea {}
        Rectangle { background: blue; }
    }

    handle := Rectangle {
        x: r1.width;
        height: 100%;
        width: 8px;
        z:100;
        background: @linear-gradient(0deg, #ddd, #aaa );

        out property <float> new_proportion:ta.new_proportion;
        out property <bool> pressed:ta.pressed;

        ta:=TouchArea{
            property <float> new_proportion: max(0.05, min(0.95, proportion + (self.mouse_x - self.pressed_x) / root.width));
            clicked => {
                root.proportion=self.new_proportion;
                debug("ta clicked")
            }
        }
    }

    r2 := Rectangle {
        height: 100%;
        width: (1 - actual_proportion) * parent.width - handle.width / 2;
        x: handle.x + handle.width;
        TouchArea {}
        Rectangle { background: red; }
    }
    // This area covers the whole rectangle, but there it can only be clicked form the handle because
    // there is a TouchArea in sub rectangles
    touch := TouchArea {
        property <float> new_proportion: max(0.05, min(0.95, proportion + (self.mouse_x - self.pressed_x) / root.width));
        clicked => {
            proportion = new_proportion;
            debug("clicked")
        }
    }
}

export component AppWindow inherits Window {
    title: "Tsukuyomi";
    icon: Icons.default;
    

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {};
            }
            MenuItem {
                title: @tr("Open");
                activated => {};
            }
            MenuItem {
                title: @tr("Open Recentry");
                activated => {};
            }
            MenuSeparator {}
            MenuItem {
                title: @tr("Save");
                activated =>MenuBarActions.save();
            }
            MenuItem {
                title: @tr("Save As");
                activated => {};
            }
        }
        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Undo");
                activated => {};
            }
            MenuItem {
                title: @tr("Redo");
                activated => {};
            }
            MenuItem {
                title: @tr("Copy");
                activated => {};
            }
            MenuItem {
                title: @tr("Paste");
                activated => {};
            }
        }
        Menu {
            title: @tr("Help");
            MenuItem {
                title: @tr("About");
                activated => {};
            }
        }
    }// MenuBar

    

    VerticalLayout{
        TopBar {}
        main-pane:=TabWidget {
            height: 70%;
            width:100%;
            Tab {
                title: @tr("Fixtures");
                FixturesTab {}
            }
            Tab {
                title: @tr("Functions");
                FunctionsTab {}
            }
            Tab {
                title: @tr("TimeLine");
                TimeLineView {}
            }
            Tab {
                title: @tr("Virtual Console");
                VirtualConsoleTab {}
            }
        }
        
        Rectangle {
            drop-shadow-blur: 0.2rem;
            drop-shadow-color: Palette.background;
            height: 30%;

            HorizontalLayout {
                //height: 30%;
                HorizontalSplit {}
                
                Preview2D {}
                FunctionView {}
            }
        }
    }
}
