import { Button, VerticalBox, TabWidget, HorizontalBox, Palette } from "std-widgets.slint";
import { FixturesTab } from "fixtures-tab.slint";
import { FunctionsTab } from "functions-tab.slint";
import { VirtualConsoleTab } from "virtual-console-tab.slint";
import { Preview2D } from "views/preview-2d.slint";
import { FunctionView } from "views/function-view.slint";
import { TkPalette, Icons } from "styling.slint";
import { TopBar } from "top-bar.slint";

export global MenuBarActions {
    callback save();
    callback save-as();
}

export component AppWindow inherits Window {
    title: "Tsukuyomi";
    icon: Icons.default;
    //background: TkPalette.background;
    

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {};
            }
            MenuItem {
                title: @tr("Open");
                activated => {};
            }
            MenuItem {
                title: @tr("Open Recentry");
                activated => {};
            }
            MenuSeparator {}
            MenuItem {
                title: @tr("Save");
                activated =>MenuBarActions.save();
            }
            MenuItem {
                title: @tr("Save As");
                activated => {};
            }
        }
        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Undo");
                activated => {};
            }
            MenuItem {
                title: @tr("Redo");
                activated => {};
            }
            MenuItem {
                title: @tr("Copy");
                activated => {};
            }
            MenuItem {
                title: @tr("Paste");
                activated => {};
            }
        }
        Menu {
            title: @tr("Help");
            MenuItem {
                title: @tr("About");
                activated => {};
            }
        }
    }// MenuBar

    

    VerticalBox{
        TopBar {
            toggle-color-scheme => {
                Palette.color-scheme=Palette.color-scheme==ColorScheme.dark?ColorScheme.light:ColorScheme.dark
            }
        }
        TabWidget {
            height: 70%;
            preferred-width: 10px;
            Tab {
                title: @tr("Fixtures");
                FixturesTab {}
            }
            Tab {
                title: @tr("Functions");
                FunctionsTab {}
            }
            Tab {
                title: @tr("Virtual Console");
                VirtualConsoleTab {}
            }
        }
        HorizontalBox {
            height: 30%;
            Preview2D {}
            FunctionView {}
        }
    }
}
