import { TabWidget, Palette } from "std-widgets.slint";
import { FixtureListView } from "views/fixture-list-view.slint";
import { UniverseView } from "views/universe-view.slint";
import { BorderVert } from "styling.slint";

export component FixturesTab inherits Rectangle {
    HorizontalLayout {
        FixtureListView {
            width: 30%;
        }

        BorderVert { }

        UniverseView {
            width: 65%;
        }
    }
}
