import {TabWidget,Palette} from "std-widgets.slint";
import { FixtureListView } from "views/fixture-list-view.slint";
import { UniverseView } from "views/universe-view.slint";

export component FixturesTab inherits Rectangle {
    HorizontalLayout {
        FixtureListView {
            width: 30%;
        }
        
        border:=Rectangle {
            width: 1px;
            border-width: 1px;
            border-color: Palette.border;
        }
        
        UniverseView {
            width: 70%;
        }
    }
}