import { Palette } from "std-widgets.slint";

export global TkStyleMetrics {
    out property <length> layout-spacing: 8px;
    out property <length> layout-padding: 8px;
    out property <length> text-cursor-width: 1px;
    out property <color> window-background: Palette.background;
    out property <color> default-text-color: Palette.foreground;
    out property <color> textedit-background: Palette.background;
    out property <color> textedit-text-color: Palette.foreground;
    out property <bool> dark-color-scheme: Palette.color-scheme == ColorScheme.dark;
}

export global FontSettings {
    out property <relative-font-size> font-size:1.3rem;
}

export global Icons {
    out property <image> default:@image-url("../assets/icon.svg");
    out property <image> dark-mode:@image-url("../assets/dark_mode.png");
    out property <image> light-mode:@image-url("../assets/light_mode.png");
    out property <image> arrow-right:@image-url("../assets/arrow_right_24dp_E6E1E5_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> arrow-drop-down:@image-url("../assets/arrow_drop_down_24dp_E6E1E5_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> minimize:@image-url("../assets/fluent_segoe_chrome_minimize.svg");
    out property <image> maximize:@image-url("../assets/fluent_segoe_chrome_maximize.svg");
    out property <image> close:@image-url("../assets/fluent_segoe_chrome_close.svg");
}

export component PlaneText inherits Text{
    font-size: 1.25rem;
    font-weight: 400;
}

export component MiddleText inherits Text {
    font-size: 1.5rem;
    font-weight: 450;
}

export component LargeText inherits Text {
    font-size: 1.75rem;
    font-weight: 500;
}

// FIXME: orientationプロパティを持たせる
export component BorderHorz inherits Rectangle{
    width: 2px;
    background: Palette.border;
}

export component BorderVert inherits Rectangle {
    height: 2px;
    background: Palette.border;
}