import { Button,Palette } from "std-widgets.slint";
import { Icons } from "styling.slint";
export component TopBar inherits Rectangle {
    function toggle-color-scheme(){
        if Palette.color-scheme==ColorScheme.dark{
            Palette.color-scheme=ColorScheme.light;
            btn.icon=Icons.dark-mode;
        }else{
            Palette.color-scheme=ColorScheme.dark;
            btn.icon=Icons.light-mode;
        }
    }
    btn:=Button {
        icon: Icons.dark-mode;
        clicked => toggle-color-scheme();
    }
}