import "../assets/fonts/Inter-VariableFont_opsz,wght.ttf";

import { Button, TabWidget, Palette, StandardButton } from "std-widgets.slint";
import { EditorTab } from "editor-tab.slint";
import { VirtualConsoleTab } from "virtual-console-tab.slint";
import { Preview2D } from "views/preview-2d.slint";
import { FadersView } from "views/faders-view.slint";
import {
    Icons,
    BorderHorz,
    BorderVert,
    Theme,
} from "styling.slint";
import { TimeLineTab } from "timeline-tab.slint";
import { ToolTipArea } from "parts/tooltip.slint";
import { TitleBar } from "titlebar.slint";
import { MiddleText } from "parts/texts.slint";
import { LeftPanel } from "panel-left.slint";
import { Preview3D } from "views/preview-3d.slint";

export { Preview2DStore } from "./views/preview-2d.slint";
export { FadersStore } from "./views/faders-view.slint";
export { FixtureListStore } from "./containers/fixture-def-panel.slint";

export global MenuBarActions {
    callback save();
    callback save-as();
}

export component AppWindow inherits Window {
    title: "Tsukuyomi";
    icon: Icons.default;
    no-frame: true;
    full-screen: true;
    default-font-family: "Inter";
    property <bool> showSaveDialog;
    in property <image> texture;
    callback start_drag();
    callback minimize();
    callback toggle-fullscreen();
    callback close();

    if Platform.os == OperatingSystemType.macos:MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Open");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Open Recentry");
                activated => {
                };
            }

            MenuSeparator { }

            MenuItem {
                title: @tr("Save");
                activated => {
                    showSaveDialog = true;
                };
            }

            MenuItem {
                title: @tr("Save As");
                activated => {
                };
            }
        }

        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Undo");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Redo");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Copy");
                activated => {
                };
            }

            MenuItem {
                title: @tr("Paste");
                activated => {
                };
            }
        }

        Menu {
            title: @tr("Help");
            MenuItem {
                title: @tr("About");
                activated => {
                };
            }
        }
    }

    visual-elements := VerticalLayout {
        if Platform.os != OperatingSystemType.macos:title-bar := VerticalLayout {
            TitleBar {
                height: 32px;
                minimize => root.minimize();
                toggle-fullscreen => root.toggle-fullscreen();
                close => root.close();
                show-tooltip(has-hover, x, y, msg) => tooltip.show-tooltip(has-hover, x, y, msg);
                //TODO: バケツリレー
            }

            BorderHorz { }
        }

        content := HorizontalLayout {
            left := LeftPanel {
                width: self.is-expanded ? content.width * 0.25 : 52px;
                // FIXME: hard code
                show-tooltip(has-hover, x, y, msg) => tooltip.show-tooltip(has-hover, x, y, msg);
            }

            BorderVert { }

            center := VerticalLayout {
                main-pane := TabWidget {
                    //height: 70%;
                    Tab {
                        title: @tr("Editor");
                        EditorTab {
                            texture: root.texture;
                            // FIXME: バケツリレー
                        }
                    }

                    Tab {
                        title: @tr("TimeLine");
                        TimeLineTab { }
                    }

                    Tab {
                        title: @tr("Virtual Console");
                        VirtualConsoleTab { }
                    }
                }

                BorderHorz { }

                bottom-panel := HorizontalLayout {
                    //height: 30%;
                    //HorizontalSplit {}

                    Rectangle {
                        Text {
                            text: "something?";
                        }
                    }

                    BorderVert { }

                    FadersView { }
                }
            }
        }
    }

    /*TouchArea {
        moved => {
            root.start_drag();
        }
    }*/

    save-dialog := Dialog {
        visible: root.showSaveDialog;
        MiddleText {
            text: @tr("Do you want to save before exit?");
        }

        StandardButton {
            kind: StandardButtonKind.yes;
        }

        StandardButton {
            kind: StandardButtonKind.no;
        }

        StandardButton {
            kind: StandardButtonKind.cancel;
            clicked => {
                save-dialog.visible = false;
            }
        }
    }

    tooltip := ToolTipArea { }
}
