import { LeftSideBar } from "left-side-bar.slint";
import { FixtureListView } from "views/fixture-list-view.slint";
import { BorderVert, BorderHorz } from "styling.slint";
import { FixtureDefPanel } from "./containers/fixture-def-panel.slint";
export component LeftPanel inherits Rectangle {
    // current-indexが-1のとき何も表示しない
    property <int> current-index <=> side-var.current-index;
    out property <bool> is-expanded:current-index != -1;
    callback show-tooltip(has-hover: bool, x: length, y: length, msg: string);

    HorizontalLayout {
        side-var := LeftSideBar {
            show-tooltip(has-hover, x, y, msg) => root.show-tooltip(has-hover, x, y, msg);
        }

        BorderVert { }

        if current-index != -1: content := Rectangle {
            if current-index == 0:fixture-panel := FixtureDefPanel { }
            if current-index == 1:function-panel := Rectangle {
                Text {
                    text: "this is function list view!";
                }
            }
        }
    }
}
