import { Icons } from "styling.slint";
import { TabWidget } from "std-widgets.slint";
import { FixtureListView } from "views/fixture-list-view.slint";
export component SideBar inherits Rectangle {
    TabWidget {
        //orientation: Orientation.vertical;
        Tab {
            title: @tr("Fixtures");
            FixtureListView { }
        }

        Tab {
            title: @tr("Functions");
            Rectangle { }
        }
    }
}
