import { Palette } from "std-widgets.slint";

export global TkStyleMetrics {
    out property <length> layout-spacing: 8px;
    out property <length> layout-padding: 8px;
    out property <length> text-cursor-width: 1px;
    out property <color> window-background: Palette.background;
    out property <color> default-text-color: Palette.foreground;
    out property <color> textedit-background: Palette.background;
    out property <color> textedit-text-color: Palette.foreground;
    out property <bool> dark-color-scheme: Palette.color-scheme == ColorScheme.dark;
}

export global Theme {
    out property <color> tooltip-background: white;
}

export global FontSettings {
    out property <relative-font-size> font-size:1.3rem;
}

export global Icons {
    out property <image> default:@image-url("../assets/icons/icon.svg");
    out property <image> dark-mode:@image-url("../assets/icons/dark_mode.png");
    out property <image> light-mode:@image-url("../assets/icons/light_mode.png");
    out property <image> arrow-right:@image-url("../assets/icons/arrow_right_24dp_E6E1E5_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> arrow-drop-down:@image-url("../assets/icons/arrow_drop_down_24dp_E6E1E5_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> minimize:@image-url("../assets/icons/fluent_segoe_chrome_minimize.svg");
    out property <image> maximize:@image-url("../assets/icons/fluent_segoe_chrome_maximize.svg");
    out property <image> close:@image-url("../assets/icons/fluent_segoe_chrome_close.svg");
}



// FIXME: orientationプロパティを持たせる
export component BorderHorz inherits Rectangle {
    width: 2px;
    background: Palette.border;
}

export component BorderVert inherits Rectangle {
    height: 2px;
    background: Palette.border;
}
